# Generated by Django 4.1.3 on 2022-12-02 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("persona", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mantenimiento",
            fields=[
                ("id_mate", models.AutoField(primary_key=True, serialize=False)),
                ("descipcion", models.CharField(max_length=85)),
                ("fecha", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "placa",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("marca", models.CharField(max_length=65)),
                ("modelo", models.CharField(max_length=65)),
                ("tipo", models.CharField(max_length=45)),
                ("color", models.CharField(max_length=65)),
                ("cc", models.IntegerField(blank=True)),
                (
                    "mantenimiento",
                    models.ManyToManyField(blank=True, to="vehiculo.mantenimiento"),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="persona.persona",
                    ),
                ),
            ],
        ),
    ]
